//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeAccountWS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", ConfigurationName="EmployeeAccountWS.EmployeeAccountWebService_Port")]
    public interface EmployeeAccountWebService_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService:EmployeeExists", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeAccountWS.EmployeeExists_Result> EmployeeExistsAsync(EmployeeAccountWS.EmployeeExists request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService:EmployeeAccount" +
            "IsActive", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeAccountWS.EmployeeAccountIsActive_Result> EmployeeAccountIsActiveAsync(EmployeeAccountWS.EmployeeAccountIsActive request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService:GetCleanedEmplo" +
            "yeeNo", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeAccountWS.GetCleanedEmployeeNo_Result> GetCleanedEmployeeNoAsync(EmployeeAccountWS.GetCleanedEmployeeNo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService:GetEmployeeName" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeAccountWS.GetEmployeeName_Result> GetEmployeeNameAsync(EmployeeAccountWS.GetEmployeeName request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService:GetEmployeeGend" +
            "er", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeAccountWS.GetEmployeeGender_Result> GetEmployeeGenderAsync(EmployeeAccountWS.GetEmployeeGender request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService:GetEmployeeDate" +
            "OfBirth", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeAccountWS.GetEmployeeDateOfBirth_Result> GetEmployeeDateOfBirthAsync(EmployeeAccountWS.GetEmployeeDateOfBirth request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService:GetEmployeeAge", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeAccountWS.GetEmployeeAge_Result> GetEmployeeAgeAsync(EmployeeAccountWS.GetEmployeeAge request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService:GetEmployeeReti" +
            "rementDate", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeAccountWS.GetEmployeeRetirementDate_Result> GetEmployeeRetirementDateAsync(EmployeeAccountWS.GetEmployeeRetirementDate request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService:GetEmployeeEmai" +
            "lAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeAccountWS.GetEmployeeEmailAddress_Result> GetEmployeeEmailAddressAsync(EmployeeAccountWS.GetEmployeeEmailAddress request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService:GetEmployeeUser" +
            "ID", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeAccountWS.GetEmployeeUserID_Result> GetEmployeeUserIDAsync(EmployeeAccountWS.GetEmployeeUserID request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService:CreateEmployeeD" +
            "irectory", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeAccountWS.CreateEmployeeDirectory_Result> CreateEmployeeDirectoryAsync(EmployeeAccountWS.CreateEmployeeDirectory request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService:LoginEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeAccountWS.LoginEmployee_Result> LoginEmployeeAsync(EmployeeAccountWS.LoginEmployee request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService:LoginEmployeeCo" +
            "re", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeAccountWS.LoginEmployeeCore_Result> LoginEmployeeCoreAsync(EmployeeAccountWS.LoginEmployeeCore request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService:IsEmployeeDefau" +
            "ltPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeAccountWS.IsEmployeeDefaultPassword_Result> IsEmployeeDefaultPasswordAsync(EmployeeAccountWS.IsEmployeeDefaultPassword request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService:SetPasswordRese" +
            "tToken", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeAccountWS.SetPasswordResetToken_Result> SetPasswordResetTokenAsync(EmployeeAccountWS.SetPasswordResetToken request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService:GetPasswordRese" +
            "tToken", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeAccountWS.GetPasswordResetToken_Result> GetPasswordResetTokenAsync(EmployeeAccountWS.GetPasswordResetToken request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService:IsPasswordReset" +
            "TokenExpired", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeAccountWS.IsPasswordResetTokenExpired_Result> IsPasswordResetTokenExpiredAsync(EmployeeAccountWS.IsPasswordResetTokenExpired request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService:SendPasswordRes" +
            "etLink", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeAccountWS.SendPasswordResetLink_Result> SendPasswordResetLinkAsync(EmployeeAccountWS.SendPasswordResetLink request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService:ResetEmployeePo" +
            "rtalPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeAccountWS.ResetEmployeePortalPassword_Result> ResetEmployeePortalPasswordAsync(EmployeeAccountWS.ResetEmployeePortalPassword request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeExists", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class EmployeeExists
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public string employeeNoa46;
        
        public EmployeeExists()
        {
        }
        
        public EmployeeExists(string employeeNoa46)
        {
            this.employeeNoa46 = employeeNoa46;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeExists_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class EmployeeExists_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public bool return_value;
        
        public EmployeeExists_Result()
        {
        }
        
        public EmployeeExists_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeAccountIsActive", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class EmployeeAccountIsActive
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public string employeeNoa46;
        
        public EmployeeAccountIsActive()
        {
        }
        
        public EmployeeAccountIsActive(string employeeNoa46)
        {
            this.employeeNoa46 = employeeNoa46;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeAccountIsActive_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class EmployeeAccountIsActive_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public bool return_value;
        
        public EmployeeAccountIsActive_Result()
        {
        }
        
        public EmployeeAccountIsActive_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCleanedEmployeeNo", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class GetCleanedEmployeeNo
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public string employeeNoa46;
        
        public GetCleanedEmployeeNo()
        {
        }
        
        public GetCleanedEmployeeNo(string employeeNoa46)
        {
            this.employeeNoa46 = employeeNoa46;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCleanedEmployeeNo_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class GetCleanedEmployeeNo_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public string return_value;
        
        public GetCleanedEmployeeNo_Result()
        {
        }
        
        public GetCleanedEmployeeNo_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeeName", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class GetEmployeeName
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public string employeeNoa46;
        
        public GetEmployeeName()
        {
        }
        
        public GetEmployeeName(string employeeNoa46)
        {
            this.employeeNoa46 = employeeNoa46;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeeName_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class GetEmployeeName_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public string return_value;
        
        public GetEmployeeName_Result()
        {
        }
        
        public GetEmployeeName_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeeGender", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class GetEmployeeGender
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public string employeeNoa46;
        
        public GetEmployeeGender()
        {
        }
        
        public GetEmployeeGender(string employeeNoa46)
        {
            this.employeeNoa46 = employeeNoa46;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeeGender_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class GetEmployeeGender_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public string return_value;
        
        public GetEmployeeGender_Result()
        {
        }
        
        public GetEmployeeGender_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeeDateOfBirth", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class GetEmployeeDateOfBirth
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public string employeeNoa46;
        
        public GetEmployeeDateOfBirth()
        {
        }
        
        public GetEmployeeDateOfBirth(string employeeNoa46)
        {
            this.employeeNoa46 = employeeNoa46;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeeDateOfBirth_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class GetEmployeeDateOfBirth_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public string return_value;
        
        public GetEmployeeDateOfBirth_Result()
        {
        }
        
        public GetEmployeeDateOfBirth_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeeAge", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class GetEmployeeAge
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public string employeeNoa46;
        
        public GetEmployeeAge()
        {
        }
        
        public GetEmployeeAge(string employeeNoa46)
        {
            this.employeeNoa46 = employeeNoa46;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeeAge_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class GetEmployeeAge_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public string return_value;
        
        public GetEmployeeAge_Result()
        {
        }
        
        public GetEmployeeAge_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeeRetirementDate", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class GetEmployeeRetirementDate
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public string employeeNoa46;
        
        public GetEmployeeRetirementDate()
        {
        }
        
        public GetEmployeeRetirementDate(string employeeNoa46)
        {
            this.employeeNoa46 = employeeNoa46;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeeRetirementDate_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class GetEmployeeRetirementDate_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public string return_value;
        
        public GetEmployeeRetirementDate_Result()
        {
        }
        
        public GetEmployeeRetirementDate_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeeEmailAddress", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class GetEmployeeEmailAddress
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public string employeeNoa46;
        
        public GetEmployeeEmailAddress()
        {
        }
        
        public GetEmployeeEmailAddress(string employeeNoa46)
        {
            this.employeeNoa46 = employeeNoa46;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeeEmailAddress_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class GetEmployeeEmailAddress_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public string return_value;
        
        public GetEmployeeEmailAddress_Result()
        {
        }
        
        public GetEmployeeEmailAddress_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeeUserID", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class GetEmployeeUserID
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public string employeeNoa46;
        
        public GetEmployeeUserID()
        {
        }
        
        public GetEmployeeUserID(string employeeNoa46)
        {
            this.employeeNoa46 = employeeNoa46;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeeUserID_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class GetEmployeeUserID_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public string return_value;
        
        public GetEmployeeUserID_Result()
        {
        }
        
        public GetEmployeeUserID_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateEmployeeDirectory", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class CreateEmployeeDirectory
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public string employeeNoa46;
        
        public CreateEmployeeDirectory()
        {
        }
        
        public CreateEmployeeDirectory(string employeeNoa46)
        {
            this.employeeNoa46 = employeeNoa46;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateEmployeeDirectory_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class CreateEmployeeDirectory_Result
    {
        
        public CreateEmployeeDirectory_Result()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginEmployee", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class LoginEmployee
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public string employeeNoa46;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=1)]
        public string password;
        
        public LoginEmployee()
        {
        }
        
        public LoginEmployee(string employeeNoa46, string password)
        {
            this.employeeNoa46 = employeeNoa46;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginEmployee_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class LoginEmployee_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public bool return_value;
        
        public LoginEmployee_Result()
        {
        }
        
        public LoginEmployee_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginEmployeeCore", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class LoginEmployeeCore
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public string pK;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=1)]
        public string pW;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=2)]
        public string mail;
        
        public LoginEmployeeCore()
        {
        }
        
        public LoginEmployeeCore(string pK, string pW, string mail)
        {
            this.pK = pK;
            this.pW = pW;
            this.mail = mail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginEmployeeCore_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class LoginEmployeeCore_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public string return_value;
        
        public LoginEmployeeCore_Result()
        {
        }
        
        public LoginEmployeeCore_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsEmployeeDefaultPassword", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class IsEmployeeDefaultPassword
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public string employeeNoa46;
        
        public IsEmployeeDefaultPassword()
        {
        }
        
        public IsEmployeeDefaultPassword(string employeeNoa46)
        {
            this.employeeNoa46 = employeeNoa46;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsEmployeeDefaultPassword_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class IsEmployeeDefaultPassword_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public bool return_value;
        
        public IsEmployeeDefaultPassword_Result()
        {
        }
        
        public IsEmployeeDefaultPassword_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetPasswordResetToken", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class SetPasswordResetToken
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public string employeeNoa46;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=1)]
        public string passwordResetToken;
        
        public SetPasswordResetToken()
        {
        }
        
        public SetPasswordResetToken(string employeeNoa46, string passwordResetToken)
        {
            this.employeeNoa46 = employeeNoa46;
            this.passwordResetToken = passwordResetToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetPasswordResetToken_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class SetPasswordResetToken_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public bool return_value;
        
        public SetPasswordResetToken_Result()
        {
        }
        
        public SetPasswordResetToken_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPasswordResetToken", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class GetPasswordResetToken
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public string employeeNoa46;
        
        public GetPasswordResetToken()
        {
        }
        
        public GetPasswordResetToken(string employeeNoa46)
        {
            this.employeeNoa46 = employeeNoa46;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPasswordResetToken_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class GetPasswordResetToken_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public string return_value;
        
        public GetPasswordResetToken_Result()
        {
        }
        
        public GetPasswordResetToken_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsPasswordResetTokenExpired", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class IsPasswordResetTokenExpired
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public string employeeNoa46;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=1)]
        public string passwordResetToken;
        
        public IsPasswordResetTokenExpired()
        {
        }
        
        public IsPasswordResetTokenExpired(string employeeNoa46, string passwordResetToken)
        {
            this.employeeNoa46 = employeeNoa46;
            this.passwordResetToken = passwordResetToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsPasswordResetTokenExpired_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class IsPasswordResetTokenExpired_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public bool return_value;
        
        public IsPasswordResetTokenExpired_Result()
        {
        }
        
        public IsPasswordResetTokenExpired_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendPasswordResetLink", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class SendPasswordResetLink
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public string employeeNoa46;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=1)]
        public string emailMessage;
        
        public SendPasswordResetLink()
        {
        }
        
        public SendPasswordResetLink(string employeeNoa46, string emailMessage)
        {
            this.employeeNoa46 = employeeNoa46;
            this.emailMessage = emailMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendPasswordResetLink_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class SendPasswordResetLink_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public bool return_value;
        
        public SendPasswordResetLink_Result()
        {
        }
        
        public SendPasswordResetLink_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetEmployeePortalPassword", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class ResetEmployeePortalPassword
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public string employeeNoa46;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=1)]
        public string newPassword;
        
        public ResetEmployeePortalPassword()
        {
        }
        
        public ResetEmployeePortalPassword(string employeeNoa46, string newPassword)
        {
            this.employeeNoa46 = employeeNoa46;
            this.newPassword = newPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetEmployeePortalPassword_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", IsWrapped=true)]
    public partial class ResetEmployeePortalPassword_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/EmployeeAccountWebService", Order=0)]
        public bool return_value;
        
        public ResetEmployeePortalPassword_Result()
        {
        }
        
        public ResetEmployeePortalPassword_Result(bool return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface EmployeeAccountWebService_PortChannel : EmployeeAccountWS.EmployeeAccountWebService_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class EmployeeAccountWebService_PortClient : System.ServiceModel.ClientBase<EmployeeAccountWS.EmployeeAccountWebService_Port>, EmployeeAccountWS.EmployeeAccountWebService_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EmployeeAccountWebService_PortClient() : 
                base(EmployeeAccountWebService_PortClient.GetDefaultBinding(), EmployeeAccountWebService_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.EmployeeAccountWebService_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmployeeAccountWebService_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(EmployeeAccountWebService_PortClient.GetBindingForEndpoint(endpointConfiguration), EmployeeAccountWebService_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmployeeAccountWebService_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EmployeeAccountWebService_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmployeeAccountWebService_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EmployeeAccountWebService_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmployeeAccountWebService_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeAccountWS.EmployeeExists_Result> EmployeeAccountWS.EmployeeAccountWebService_Port.EmployeeExistsAsync(EmployeeAccountWS.EmployeeExists request)
        {
            return base.Channel.EmployeeExistsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeAccountWS.EmployeeExists_Result> EmployeeExistsAsync(string employeeNoa46)
        {
            EmployeeAccountWS.EmployeeExists inValue = new EmployeeAccountWS.EmployeeExists();
            inValue.employeeNoa46 = employeeNoa46;
            return ((EmployeeAccountWS.EmployeeAccountWebService_Port)(this)).EmployeeExistsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeAccountWS.EmployeeAccountIsActive_Result> EmployeeAccountWS.EmployeeAccountWebService_Port.EmployeeAccountIsActiveAsync(EmployeeAccountWS.EmployeeAccountIsActive request)
        {
            return base.Channel.EmployeeAccountIsActiveAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeAccountWS.EmployeeAccountIsActive_Result> EmployeeAccountIsActiveAsync(string employeeNoa46)
        {
            EmployeeAccountWS.EmployeeAccountIsActive inValue = new EmployeeAccountWS.EmployeeAccountIsActive();
            inValue.employeeNoa46 = employeeNoa46;
            return ((EmployeeAccountWS.EmployeeAccountWebService_Port)(this)).EmployeeAccountIsActiveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeAccountWS.GetCleanedEmployeeNo_Result> EmployeeAccountWS.EmployeeAccountWebService_Port.GetCleanedEmployeeNoAsync(EmployeeAccountWS.GetCleanedEmployeeNo request)
        {
            return base.Channel.GetCleanedEmployeeNoAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeAccountWS.GetCleanedEmployeeNo_Result> GetCleanedEmployeeNoAsync(string employeeNoa46)
        {
            EmployeeAccountWS.GetCleanedEmployeeNo inValue = new EmployeeAccountWS.GetCleanedEmployeeNo();
            inValue.employeeNoa46 = employeeNoa46;
            return ((EmployeeAccountWS.EmployeeAccountWebService_Port)(this)).GetCleanedEmployeeNoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeAccountWS.GetEmployeeName_Result> EmployeeAccountWS.EmployeeAccountWebService_Port.GetEmployeeNameAsync(EmployeeAccountWS.GetEmployeeName request)
        {
            return base.Channel.GetEmployeeNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeAccountWS.GetEmployeeName_Result> GetEmployeeNameAsync(string employeeNoa46)
        {
            EmployeeAccountWS.GetEmployeeName inValue = new EmployeeAccountWS.GetEmployeeName();
            inValue.employeeNoa46 = employeeNoa46;
            return ((EmployeeAccountWS.EmployeeAccountWebService_Port)(this)).GetEmployeeNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeAccountWS.GetEmployeeGender_Result> EmployeeAccountWS.EmployeeAccountWebService_Port.GetEmployeeGenderAsync(EmployeeAccountWS.GetEmployeeGender request)
        {
            return base.Channel.GetEmployeeGenderAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeAccountWS.GetEmployeeGender_Result> GetEmployeeGenderAsync(string employeeNoa46)
        {
            EmployeeAccountWS.GetEmployeeGender inValue = new EmployeeAccountWS.GetEmployeeGender();
            inValue.employeeNoa46 = employeeNoa46;
            return ((EmployeeAccountWS.EmployeeAccountWebService_Port)(this)).GetEmployeeGenderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeAccountWS.GetEmployeeDateOfBirth_Result> EmployeeAccountWS.EmployeeAccountWebService_Port.GetEmployeeDateOfBirthAsync(EmployeeAccountWS.GetEmployeeDateOfBirth request)
        {
            return base.Channel.GetEmployeeDateOfBirthAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeAccountWS.GetEmployeeDateOfBirth_Result> GetEmployeeDateOfBirthAsync(string employeeNoa46)
        {
            EmployeeAccountWS.GetEmployeeDateOfBirth inValue = new EmployeeAccountWS.GetEmployeeDateOfBirth();
            inValue.employeeNoa46 = employeeNoa46;
            return ((EmployeeAccountWS.EmployeeAccountWebService_Port)(this)).GetEmployeeDateOfBirthAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeAccountWS.GetEmployeeAge_Result> EmployeeAccountWS.EmployeeAccountWebService_Port.GetEmployeeAgeAsync(EmployeeAccountWS.GetEmployeeAge request)
        {
            return base.Channel.GetEmployeeAgeAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeAccountWS.GetEmployeeAge_Result> GetEmployeeAgeAsync(string employeeNoa46)
        {
            EmployeeAccountWS.GetEmployeeAge inValue = new EmployeeAccountWS.GetEmployeeAge();
            inValue.employeeNoa46 = employeeNoa46;
            return ((EmployeeAccountWS.EmployeeAccountWebService_Port)(this)).GetEmployeeAgeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeAccountWS.GetEmployeeRetirementDate_Result> EmployeeAccountWS.EmployeeAccountWebService_Port.GetEmployeeRetirementDateAsync(EmployeeAccountWS.GetEmployeeRetirementDate request)
        {
            return base.Channel.GetEmployeeRetirementDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeAccountWS.GetEmployeeRetirementDate_Result> GetEmployeeRetirementDateAsync(string employeeNoa46)
        {
            EmployeeAccountWS.GetEmployeeRetirementDate inValue = new EmployeeAccountWS.GetEmployeeRetirementDate();
            inValue.employeeNoa46 = employeeNoa46;
            return ((EmployeeAccountWS.EmployeeAccountWebService_Port)(this)).GetEmployeeRetirementDateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeAccountWS.GetEmployeeEmailAddress_Result> EmployeeAccountWS.EmployeeAccountWebService_Port.GetEmployeeEmailAddressAsync(EmployeeAccountWS.GetEmployeeEmailAddress request)
        {
            return base.Channel.GetEmployeeEmailAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeAccountWS.GetEmployeeEmailAddress_Result> GetEmployeeEmailAddressAsync(string employeeNoa46)
        {
            EmployeeAccountWS.GetEmployeeEmailAddress inValue = new EmployeeAccountWS.GetEmployeeEmailAddress();
            inValue.employeeNoa46 = employeeNoa46;
            return ((EmployeeAccountWS.EmployeeAccountWebService_Port)(this)).GetEmployeeEmailAddressAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeAccountWS.GetEmployeeUserID_Result> EmployeeAccountWS.EmployeeAccountWebService_Port.GetEmployeeUserIDAsync(EmployeeAccountWS.GetEmployeeUserID request)
        {
            return base.Channel.GetEmployeeUserIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeAccountWS.GetEmployeeUserID_Result> GetEmployeeUserIDAsync(string employeeNoa46)
        {
            EmployeeAccountWS.GetEmployeeUserID inValue = new EmployeeAccountWS.GetEmployeeUserID();
            inValue.employeeNoa46 = employeeNoa46;
            return ((EmployeeAccountWS.EmployeeAccountWebService_Port)(this)).GetEmployeeUserIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeAccountWS.CreateEmployeeDirectory_Result> EmployeeAccountWS.EmployeeAccountWebService_Port.CreateEmployeeDirectoryAsync(EmployeeAccountWS.CreateEmployeeDirectory request)
        {
            return base.Channel.CreateEmployeeDirectoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeAccountWS.CreateEmployeeDirectory_Result> CreateEmployeeDirectoryAsync(string employeeNoa46)
        {
            EmployeeAccountWS.CreateEmployeeDirectory inValue = new EmployeeAccountWS.CreateEmployeeDirectory();
            inValue.employeeNoa46 = employeeNoa46;
            return ((EmployeeAccountWS.EmployeeAccountWebService_Port)(this)).CreateEmployeeDirectoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeAccountWS.LoginEmployee_Result> EmployeeAccountWS.EmployeeAccountWebService_Port.LoginEmployeeAsync(EmployeeAccountWS.LoginEmployee request)
        {
            return base.Channel.LoginEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeAccountWS.LoginEmployee_Result> LoginEmployeeAsync(string employeeNoa46, string password)
        {
            EmployeeAccountWS.LoginEmployee inValue = new EmployeeAccountWS.LoginEmployee();
            inValue.employeeNoa46 = employeeNoa46;
            inValue.password = password;
            return ((EmployeeAccountWS.EmployeeAccountWebService_Port)(this)).LoginEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeAccountWS.LoginEmployeeCore_Result> EmployeeAccountWS.EmployeeAccountWebService_Port.LoginEmployeeCoreAsync(EmployeeAccountWS.LoginEmployeeCore request)
        {
            return base.Channel.LoginEmployeeCoreAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeAccountWS.LoginEmployeeCore_Result> LoginEmployeeCoreAsync(string pK, string pW, string mail)
        {
            EmployeeAccountWS.LoginEmployeeCore inValue = new EmployeeAccountWS.LoginEmployeeCore();
            inValue.pK = pK;
            inValue.pW = pW;
            inValue.mail = mail;
            return ((EmployeeAccountWS.EmployeeAccountWebService_Port)(this)).LoginEmployeeCoreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeAccountWS.IsEmployeeDefaultPassword_Result> EmployeeAccountWS.EmployeeAccountWebService_Port.IsEmployeeDefaultPasswordAsync(EmployeeAccountWS.IsEmployeeDefaultPassword request)
        {
            return base.Channel.IsEmployeeDefaultPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeAccountWS.IsEmployeeDefaultPassword_Result> IsEmployeeDefaultPasswordAsync(string employeeNoa46)
        {
            EmployeeAccountWS.IsEmployeeDefaultPassword inValue = new EmployeeAccountWS.IsEmployeeDefaultPassword();
            inValue.employeeNoa46 = employeeNoa46;
            return ((EmployeeAccountWS.EmployeeAccountWebService_Port)(this)).IsEmployeeDefaultPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeAccountWS.SetPasswordResetToken_Result> EmployeeAccountWS.EmployeeAccountWebService_Port.SetPasswordResetTokenAsync(EmployeeAccountWS.SetPasswordResetToken request)
        {
            return base.Channel.SetPasswordResetTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeAccountWS.SetPasswordResetToken_Result> SetPasswordResetTokenAsync(string employeeNoa46, string passwordResetToken)
        {
            EmployeeAccountWS.SetPasswordResetToken inValue = new EmployeeAccountWS.SetPasswordResetToken();
            inValue.employeeNoa46 = employeeNoa46;
            inValue.passwordResetToken = passwordResetToken;
            return ((EmployeeAccountWS.EmployeeAccountWebService_Port)(this)).SetPasswordResetTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeAccountWS.GetPasswordResetToken_Result> EmployeeAccountWS.EmployeeAccountWebService_Port.GetPasswordResetTokenAsync(EmployeeAccountWS.GetPasswordResetToken request)
        {
            return base.Channel.GetPasswordResetTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeAccountWS.GetPasswordResetToken_Result> GetPasswordResetTokenAsync(string employeeNoa46)
        {
            EmployeeAccountWS.GetPasswordResetToken inValue = new EmployeeAccountWS.GetPasswordResetToken();
            inValue.employeeNoa46 = employeeNoa46;
            return ((EmployeeAccountWS.EmployeeAccountWebService_Port)(this)).GetPasswordResetTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeAccountWS.IsPasswordResetTokenExpired_Result> EmployeeAccountWS.EmployeeAccountWebService_Port.IsPasswordResetTokenExpiredAsync(EmployeeAccountWS.IsPasswordResetTokenExpired request)
        {
            return base.Channel.IsPasswordResetTokenExpiredAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeAccountWS.IsPasswordResetTokenExpired_Result> IsPasswordResetTokenExpiredAsync(string employeeNoa46, string passwordResetToken)
        {
            EmployeeAccountWS.IsPasswordResetTokenExpired inValue = new EmployeeAccountWS.IsPasswordResetTokenExpired();
            inValue.employeeNoa46 = employeeNoa46;
            inValue.passwordResetToken = passwordResetToken;
            return ((EmployeeAccountWS.EmployeeAccountWebService_Port)(this)).IsPasswordResetTokenExpiredAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeAccountWS.SendPasswordResetLink_Result> EmployeeAccountWS.EmployeeAccountWebService_Port.SendPasswordResetLinkAsync(EmployeeAccountWS.SendPasswordResetLink request)
        {
            return base.Channel.SendPasswordResetLinkAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeAccountWS.SendPasswordResetLink_Result> SendPasswordResetLinkAsync(string employeeNoa46, string emailMessage)
        {
            EmployeeAccountWS.SendPasswordResetLink inValue = new EmployeeAccountWS.SendPasswordResetLink();
            inValue.employeeNoa46 = employeeNoa46;
            inValue.emailMessage = emailMessage;
            return ((EmployeeAccountWS.EmployeeAccountWebService_Port)(this)).SendPasswordResetLinkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeAccountWS.ResetEmployeePortalPassword_Result> EmployeeAccountWS.EmployeeAccountWebService_Port.ResetEmployeePortalPasswordAsync(EmployeeAccountWS.ResetEmployeePortalPassword request)
        {
            return base.Channel.ResetEmployeePortalPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeAccountWS.ResetEmployeePortalPassword_Result> ResetEmployeePortalPasswordAsync(string employeeNoa46, string newPassword)
        {
            EmployeeAccountWS.ResetEmployeePortalPassword inValue = new EmployeeAccountWS.ResetEmployeePortalPassword();
            inValue.employeeNoa46 = employeeNoa46;
            inValue.newPassword = newPassword;
            return ((EmployeeAccountWS.EmployeeAccountWebService_Port)(this)).ResetEmployeePortalPasswordAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EmployeeAccountWebService_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EmployeeAccountWebService_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://desktop-csglh1r:7347/PLATCORP/WS/Platcorp Training/Codeunit/EmployeeAccoun" +
                        "tWebService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EmployeeAccountWebService_PortClient.GetBindingForEndpoint(EndpointConfiguration.EmployeeAccountWebService_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EmployeeAccountWebService_PortClient.GetEndpointAddress(EndpointConfiguration.EmployeeAccountWebService_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            EmployeeAccountWebService_Port,
        }
    }
}
