//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HREmployeeWS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/HREmployeeWebService", ConfigurationName="HREmployeeWS.HREmployeeWebService_Port")]
    public interface HREmployeeWebService_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/HREmployeeWebService:CreateEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HREmployeeWS.CreateEmployee_Result> CreateEmployeeAsync(HREmployeeWS.CreateEmployee request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/HREmployeeWebService:GetEmployeesRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HREmployeeWS.GetEmployeesRange_Result> GetEmployeesRangeAsync(HREmployeeWS.GetEmployeesRange request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/HREmployeeWebService:GetEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HREmployeeWS.GetEmployee_Result> GetEmployeeAsync(HREmployeeWS.GetEmployee request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/HREmployeeWebService:UpdateEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HREmployeeWS.UpdateEmployee_Result> UpdateEmployeeAsync(HREmployeeWS.UpdateEmployee request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/HREmployeeWebService:DeleteEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HREmployeeWS.DeleteEmployee_Result> DeleteEmployeeAsync(HREmployeeWS.DeleteEmployee request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateEmployee", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/HREmployeeWebService", IsWrapped=true)]
    public partial class CreateEmployee
    {
        
        public CreateEmployee()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateEmployee_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/HREmployeeWebService", IsWrapped=true)]
    public partial class CreateEmployee_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/HREmployeeWebService", Order=0)]
        public string return_value;
        
        public CreateEmployee_Result()
        {
        }
        
        public CreateEmployee_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeesRange", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/HREmployeeWebService", IsWrapped=true)]
    public partial class GetEmployeesRange
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/HREmployeeWebService", Order=0)]
        public int startIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/HREmployeeWebService", Order=1)]
        public int selectRange;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/HREmployeeWebService", Order=2)]
        public string employeeStatus;
        
        public GetEmployeesRange()
        {
        }
        
        public GetEmployeesRange(int startIndex, int selectRange, string employeeStatus)
        {
            this.startIndex = startIndex;
            this.selectRange = selectRange;
            this.employeeStatus = employeeStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeesRange_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/HREmployeeWebService", IsWrapped=true)]
    public partial class GetEmployeesRange_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/HREmployeeWebService", Order=0)]
        public string return_value;
        
        public GetEmployeesRange_Result()
        {
        }
        
        public GetEmployeesRange_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployee", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/HREmployeeWebService", IsWrapped=true)]
    public partial class GetEmployee
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/HREmployeeWebService", Order=0)]
        public string employeeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/HREmployeeWebService", Order=1)]
        public string employeeStatus;
        
        public GetEmployee()
        {
        }
        
        public GetEmployee(string employeeID, string employeeStatus)
        {
            this.employeeID = employeeID;
            this.employeeStatus = employeeStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployee_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/HREmployeeWebService", IsWrapped=true)]
    public partial class GetEmployee_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/HREmployeeWebService", Order=0)]
        public string return_value;
        
        public GetEmployee_Result()
        {
        }
        
        public GetEmployee_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateEmployee", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/HREmployeeWebService", IsWrapped=true)]
    public partial class UpdateEmployee
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/HREmployeeWebService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("stringArray")]
        public string[] stringArray;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/HREmployeeWebService", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("boolArray")]
        public bool[] boolArray;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/HREmployeeWebService", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("decimalArray")]
        public decimal[] decimalArray;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/HREmployeeWebService", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("integerArray")]
        public int[] integerArray;
        
        public UpdateEmployee()
        {
        }
        
        public UpdateEmployee(string[] stringArray, bool[] boolArray, decimal[] decimalArray, int[] integerArray)
        {
            this.stringArray = stringArray;
            this.boolArray = boolArray;
            this.decimalArray = decimalArray;
            this.integerArray = integerArray;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateEmployee_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/HREmployeeWebService", IsWrapped=true)]
    public partial class UpdateEmployee_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/HREmployeeWebService", Order=0)]
        public string return_value;
        
        public UpdateEmployee_Result()
        {
        }
        
        public UpdateEmployee_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteEmployee", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/HREmployeeWebService", IsWrapped=true)]
    public partial class DeleteEmployee
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/HREmployeeWebService", Order=0)]
        public string employeeID;
        
        public DeleteEmployee()
        {
        }
        
        public DeleteEmployee(string employeeID)
        {
            this.employeeID = employeeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteEmployee_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/HREmployeeWebService", IsWrapped=true)]
    public partial class DeleteEmployee_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/HREmployeeWebService", Order=0)]
        public string return_value;
        
        public DeleteEmployee_Result()
        {
        }
        
        public DeleteEmployee_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface HREmployeeWebService_PortChannel : HREmployeeWS.HREmployeeWebService_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class HREmployeeWebService_PortClient : System.ServiceModel.ClientBase<HREmployeeWS.HREmployeeWebService_Port>, HREmployeeWS.HREmployeeWebService_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public HREmployeeWebService_PortClient() : 
                base(HREmployeeWebService_PortClient.GetDefaultBinding(), HREmployeeWebService_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.HREmployeeWebService_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HREmployeeWebService_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(HREmployeeWebService_PortClient.GetBindingForEndpoint(endpointConfiguration), HREmployeeWebService_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HREmployeeWebService_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HREmployeeWebService_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HREmployeeWebService_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HREmployeeWebService_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HREmployeeWebService_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HREmployeeWS.CreateEmployee_Result> HREmployeeWS.HREmployeeWebService_Port.CreateEmployeeAsync(HREmployeeWS.CreateEmployee request)
        {
            return base.Channel.CreateEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<HREmployeeWS.CreateEmployee_Result> CreateEmployeeAsync()
        {
            HREmployeeWS.CreateEmployee inValue = new HREmployeeWS.CreateEmployee();
            return ((HREmployeeWS.HREmployeeWebService_Port)(this)).CreateEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HREmployeeWS.GetEmployeesRange_Result> HREmployeeWS.HREmployeeWebService_Port.GetEmployeesRangeAsync(HREmployeeWS.GetEmployeesRange request)
        {
            return base.Channel.GetEmployeesRangeAsync(request);
        }
        
        public System.Threading.Tasks.Task<HREmployeeWS.GetEmployeesRange_Result> GetEmployeesRangeAsync(int startIndex, int selectRange, string employeeStatus)
        {
            HREmployeeWS.GetEmployeesRange inValue = new HREmployeeWS.GetEmployeesRange();
            inValue.startIndex = startIndex;
            inValue.selectRange = selectRange;
            inValue.employeeStatus = employeeStatus;
            return ((HREmployeeWS.HREmployeeWebService_Port)(this)).GetEmployeesRangeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HREmployeeWS.GetEmployee_Result> HREmployeeWS.HREmployeeWebService_Port.GetEmployeeAsync(HREmployeeWS.GetEmployee request)
        {
            return base.Channel.GetEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<HREmployeeWS.GetEmployee_Result> GetEmployeeAsync(string employeeID, string employeeStatus)
        {
            HREmployeeWS.GetEmployee inValue = new HREmployeeWS.GetEmployee();
            inValue.employeeID = employeeID;
            inValue.employeeStatus = employeeStatus;
            return ((HREmployeeWS.HREmployeeWebService_Port)(this)).GetEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HREmployeeWS.UpdateEmployee_Result> HREmployeeWS.HREmployeeWebService_Port.UpdateEmployeeAsync(HREmployeeWS.UpdateEmployee request)
        {
            return base.Channel.UpdateEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<HREmployeeWS.UpdateEmployee_Result> UpdateEmployeeAsync(string[] stringArray, bool[] boolArray, decimal[] decimalArray, int[] integerArray)
        {
            HREmployeeWS.UpdateEmployee inValue = new HREmployeeWS.UpdateEmployee();
            inValue.stringArray = stringArray;
            inValue.boolArray = boolArray;
            inValue.decimalArray = decimalArray;
            inValue.integerArray = integerArray;
            return ((HREmployeeWS.HREmployeeWebService_Port)(this)).UpdateEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HREmployeeWS.DeleteEmployee_Result> HREmployeeWS.HREmployeeWebService_Port.DeleteEmployeeAsync(HREmployeeWS.DeleteEmployee request)
        {
            return base.Channel.DeleteEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<HREmployeeWS.DeleteEmployee_Result> DeleteEmployeeAsync(string employeeID)
        {
            HREmployeeWS.DeleteEmployee inValue = new HREmployeeWS.DeleteEmployee();
            inValue.employeeID = employeeID;
            return ((HREmployeeWS.HREmployeeWebService_Port)(this)).DeleteEmployeeAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HREmployeeWebService_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HREmployeeWebService_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://na-bee:1002/TRAININGDB/WS/Platcorp Training/Codeunit/HREmployeeWebService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return HREmployeeWebService_PortClient.GetBindingForEndpoint(EndpointConfiguration.HREmployeeWebService_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return HREmployeeWebService_PortClient.GetEndpointAddress(EndpointConfiguration.HREmployeeWebService_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            HREmployeeWebService_Port,
        }
    }
}
