//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IncidentsWS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/HRIncidentsWS", ConfigurationName="IncidentsWS.HRIncidentsWS_Port")]
    public interface HRIncidentsWS_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/HRIncidentsWS:Countries", ReplyAction="*")]
        System.Threading.Tasks.Task<IncidentsWS.Countries_Result> CountriesAsync(IncidentsWS.Countries request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/HRIncidentsWS:AllIncidences", ReplyAction="*")]
        System.Threading.Tasks.Task<IncidentsWS.AllIncidences_Result> AllIncidencesAsync(IncidentsWS.AllIncidences request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Countries", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/HRIncidentsWS", IsWrapped=true)]
    public partial class Countries
    {
        
        public Countries()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Countries_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/HRIncidentsWS", IsWrapped=true)]
    public partial class Countries_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/HRIncidentsWS", Order=0)]
        public string return_value;
        
        public Countries_Result()
        {
        }
        
        public Countries_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AllIncidences", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/HRIncidentsWS", IsWrapped=true)]
    public partial class AllIncidences
    {
        
        public AllIncidences()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AllIncidences_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/HRIncidentsWS", IsWrapped=true)]
    public partial class AllIncidences_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/HRIncidentsWS", Order=0)]
        public string return_value;
        
        public AllIncidences_Result()
        {
        }
        
        public AllIncidences_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface HRIncidentsWS_PortChannel : IncidentsWS.HRIncidentsWS_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class HRIncidentsWS_PortClient : System.ServiceModel.ClientBase<IncidentsWS.HRIncidentsWS_Port>, IncidentsWS.HRIncidentsWS_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public HRIncidentsWS_PortClient() : 
                base(HRIncidentsWS_PortClient.GetDefaultBinding(), HRIncidentsWS_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.HRIncidentsWS_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HRIncidentsWS_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(HRIncidentsWS_PortClient.GetBindingForEndpoint(endpointConfiguration), HRIncidentsWS_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HRIncidentsWS_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HRIncidentsWS_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HRIncidentsWS_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HRIncidentsWS_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HRIncidentsWS_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IncidentsWS.Countries_Result> IncidentsWS.HRIncidentsWS_Port.CountriesAsync(IncidentsWS.Countries request)
        {
            return base.Channel.CountriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<IncidentsWS.Countries_Result> CountriesAsync()
        {
            IncidentsWS.Countries inValue = new IncidentsWS.Countries();
            return ((IncidentsWS.HRIncidentsWS_Port)(this)).CountriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IncidentsWS.AllIncidences_Result> IncidentsWS.HRIncidentsWS_Port.AllIncidencesAsync(IncidentsWS.AllIncidences request)
        {
            return base.Channel.AllIncidencesAsync(request);
        }
        
        public System.Threading.Tasks.Task<IncidentsWS.AllIncidences_Result> AllIncidencesAsync()
        {
            IncidentsWS.AllIncidences inValue = new IncidentsWS.AllIncidences();
            return ((IncidentsWS.HRIncidentsWS_Port)(this)).AllIncidencesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HRIncidentsWS_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HRIncidentsWS_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://na-bee:1002/TRAININGDB/WS/Platcorp Training/Codeunit/HRIncidentsWS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return HRIncidentsWS_PortClient.GetBindingForEndpoint(EndpointConfiguration.HRIncidentsWS_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return HRIncidentsWS_PortClient.GetEndpointAddress(EndpointConfiguration.HRIncidentsWS_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            HRIncidentsWS_Port,
        }
    }
}
